kind = "web"
previewPath = "/"
title = "Spa Booking System"
version = "1.0.0"
id = "artifacts/booking-system"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 24814

[services.development]
run = "pnpm --filter @workspace/booking-system run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/booking-system", "run", "build" ]
publicDir = "artifacts/booking-system/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "24814"
BASE_PATH = "/"
